[default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 256000
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/gakonst/foundry/tree/master/config
