name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry:
    strategy:
      fail-fast: true

    name: Run Reference solutions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge Scripts
        run:  sh run_all_reference_solutions.sh
        id: run-reference-solutions
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}

